version: '3.7'

services:
  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gallery-backend
      - gallery-frontend
      - martinade

  gallery-backend:
    restart: always
    build: ./backend

  gallery-frontend:
    restart: always
    build: ./frontend

  martinade:
    restart: always
    build: ./martinade
