version: '3.7'

services:
  proxy:
    restart: always
    build: ./proxy
    ports:
      - 8000:80
      - 443:443
    depends_on:
      - gallery-backend
      - gallery-frontend
      - martinade

  gallery-backend:
    restart: always
    build:
      context: ./backend
      target: prod
    depends_on:
      - database
      - kvstore
    environment:
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_DELTA: ${JWT_EXPIRATION_DELTA}
      PIN_EXPIRATION_DELTA: ${PIN_EXPIRATION_DELTA}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}

  kvstore:
    image: redis:alpine

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}

  gallery-frontend:
    restart: always
    build:
      context: ./frontend
      target: prod

  martinade:
    restart: always
    build: ./martinade
