version: '3.7'

services:
  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

  backend:
    restart: always
    build: ./backend

  frontend:
    restart: always
    build: ./frontend
