version: '3.7'

services:
  proxy:
    restart: always
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gallery-backend
#      - gallery-frontend
#      - martinade

  gallery-backend:
    restart: always
    build:
      context: ./backend
      target: prod
    depends_on:
      - database
      - kvstore
    environment:
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_DELTA: ${JWT_EXPIRATION_DELTA}
      PIN_EXPIRATION_DELTA: ${PIN_EXPIRATION_DELTA}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}
      DATA_FOLDER: ${DATA_FOLDER}
    volumes:
      - data:${DATA_FOLDER}

  kvstore:
    image: redis:alpine

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres:/var/lib/postgresql/data

#  gallery-frontend:
#    restart: always
#    build:
#      context: ./frontend
#      target: prod
#
#  martinade:
#    restart: always
#    build: ./martinade

volumes:
  data:
  postgres:
