version: '3.7'

services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - ./src:/usr/src/app
    environment:
      PASSWORD: postgres
      DB_PORT: 5431
      DB_USER: postgres
      DB_PW: postgres

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      BASE_URL: /docs
      URL: 'http://localhost:5000/spec'
